export const dataArr:Array<object> = [
    {data: 'AC', type: 'grey', onButtonClick: 'clickAddFunc'},
    {data: '±', type: 'grey', onButtonClick: 'clickAddFunc'},
    {data: '%', type: 'grey', onButtonClick: 'clickAddFunc'},
    {data: 'ms', type: 'orange', onButtonClick: 'clickMemoryFunc'},
    {data: 'mc', type: 'dark', onButtonClick: 'clickMemoryFunc'},
    {data: 'mr', type: 'dark', onButtonClick: 'clickMemoryFunc'},
    {data: 'm-', type: 'dark', onButtonClick: 'clickMemoryFunc'},
    {data: 'm+', type: 'orange', onButtonClick: 'clickMemoryFunc'},
    {data: '7', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '8', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '9', type: 'dark', onButtonClick: 'clickNumber'},
    {data: 'x', type: 'orange', onButtonClick: 'clickOperator'},
    {data: '4', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '5', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '6', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '÷', type: 'orange', onButtonClick: 'clickOperator'},
    {data: '1', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '2', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '3', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '+', type: 'orange', onButtonClick: 'clickOperator'},
    {data: '0', type: 'dark', onButtonClick: 'clickNumber'},
    {data: '.', type: 'dark', onButtonClick: 'clickAddFunc'},
    {data: '=', type: 'dark', onButtonClick: 'clickResult'},
    {data: '+', type: 'orange', onButtonClick: 'clickOperator'},
]
